config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  devise_for :users

  resources :groups, only: [:show] do
  end

  post '/sign_up', to: 'groups#sign_up', as: :group_sign_up
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  STATUSES = %w[started recruitment_participants closed].freeze

  belongs_to :course
  has_many :participants
  has_many :users, through: :participants

  validates :title, :course_id, :start_date, :status, presence: true

  scope :recruitment_participants, -> { where(status: 'recruitment_participants') }

  def started?
    status == 'started'
  end

  def closed?
    status == 'closed'
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :participants
  has_many :groups, through: :participants
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :find_group, only: :show

  def show; end

  def sign_up
    result = ParticipantRegistration.call(
      group_id: groups_params[:id],
      email: groups_params[:email]
    )
    if result.success?
      redirect_to root_path, notice: 'Вы зарегистрированы в группе'
    else
      redirect_to root_path, notice: "Ошибка: #{result.message}"
    end
  end

  private

  def groups_params
    params.require(:group).require(:users).permit(:id, :email)
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @courses = FindCourses.new(permited_params).call
  end

  private

  def permited_params
    params.permit(:sort_by_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.slim
= simple_form_for @group, url: group_sign_up_path, method: :post do |f|
  = f.simple_fields_for :users do |u|
    = u.input :id, as: :hidden, input_html: { value: @group.id }
    = u.input :email, placeholder: 'user@domain.com'
    = u.button :submit, 'Записаться', class: 'btn btn-success'

app/views/groups/show.slim
h1 Название курса:
= @group.course.title
h2 Название группы:
= @group.title
h2 Дата старта группы:
= @group.start_date
h2 Статус:
= @group.status
h2 Колличество участников:
= @group.participants.count

br
- if user_signed_in?
  h2
  = render 'form'
- else
  p Чтобы присоединиться к группе войдите или зарегистрируйтесь
  

app/views/home/index.slim
= button_to "Сортировать по дате старта", root_path, class: "", params: { sort_by_data: true }, method: :get
- @courses.each do |course|
  h1 Название курса:
  = link_to course.title, group_path(course.group_id)
  h2 Дата начала:
  = course.start_date
  h2 Число участников:
  = course.total_participants
  hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Courses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Курсы</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= link_to 'home', root_path, class: "nav-link" %>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
      </div>
      <div class="nav-inline-item">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Войти', new_user_session_path, class: 'nav-link' %>
            <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'nav-link' %>
          <% end %>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>